### ISSUE TITLE
Refactor code to allow fearless implementation of new things

### ISSUE THREAD

**Issue by kevintakeda** [jinc0930/Clue#45]
**The terminal text-based still going to work the same way as before!**

## Refactoring allows
1. Export for the web easily.
2. Graphical.
3. Fearless implementation of new things.
4. Better testing.

## Tasks

- [x] Refactor the game logic to a new file
- [x] Make the terminal text-based also works
- [x] Unit test game logic
  - [x] items, pool, character
  - [x] rooms
  - [x] gameplay
  - [x] utils
- [x] Integrate raylib
- [x] Update readme

## To switch branches
btw you can easily switch the branch by clicking on the left bottom corner (on vscode):
![image](https://user-images.githubusercontent.com/9105388/189102131-5582b5c8-f079-472b-8858-7373e257a9c2.png)

click on main to change to **graphical**: (in case you want to contribute/review)
![image](https://user-images.githubusercontent.com/9105388/189102531-1abe0aa8-7275-4e0b-afa4-0368593b1d52.png)

also (github page):
![image](https://user-images.githubusercontent.com/9105388/189103020-3b904ef8-4ce5-4f12-ad60-f9485c7d9bb8.png)
