### ISSUE TITLE
✨ Experimental Graphics

### ISSUE THREAD

**Issue by kevintakeda** [jinc0930/Clue#47]
_We're not necessarily going to use this feature but i would like to experiment_
## Tasks
- [x] #45 
- [x] Draw things
  - [x] Map
  - [x] Items
  - [x] Dialogs
  - [x] Inventory (names)
  - [x] Call clue
  - [x] Characters (assets, names)
  - [x] Cheatsheet
- [x] Player movement (keyboard)
- [x] Take/drop item
- [x] Screen introduction
