### ISSUE TITLE
What should we do first

### ISSUE THREAD

**Issue by jinc0930** [jinc0930/Clue#48]
All the ideas are fun and interesting but what should we do first...

**Comment by kevintakeda** [comment]
[TL;DR let's start from this:](https://github.com/jinc0930/Clue/milestone/2)
- [x] #39 (the foundation for special items)
- [x] #51  
- [x] #49  (to allow funny conversations and puzzles and help make items useful)
- [ ] #50 (lastly, to make special items/coin meaningful, depends on all above)

Long ver:
First, review the pull request https://github.com/jinc0930/Clue/pull/46 which should help us add features in parallel and without fear of breaking things since we have a bunch of tests. And we can easily write more during the development.

Now, I think we can start by introducing new items or using the current ones and add functionality to them. And to obtain the special items we can create hidden puzzles.

One big question is where we want procedually random generated content vs hard coded content. I think just hard coding is easier and fun, but the game will become more predictable which i think is fine. 

I made a new tracker here #49
