### ISSUE TITLE
Dialogue graph

### ISSUE THREAD

**Issue by kevintakeda** [jinc0930/Clue#49]
Rationale:
1. To allow creation of new quests/puzzles with npcs.
2. Help make items useful  (example: trading, buying)
3. Make the game more rich by allowing game designers create rich dialogues

#### Context aware npcs
Talking with npcs should enter in a loop where each npc will have their own set of commands. Some commands have side effects that the npc MUST remember! For example:
```
me: talk bob
  bob: hey, ask me anything [ ballroom, about,  stfu ]
me: ballroom
  bob: i heard somenthing tonight do you want know more? [ yes, no, stfu ]
me: stfu
  bob: ???
me: talk bob
  bob: ....
me: talk bob
  bob: ....
```

## Directed Graph implementation
![image](https://user-images.githubusercontent.com/9105388/189714741-eecf9ef3-27f9-4618-ba74-4d8aac2bf20a.png)

### Specifics
1. NPC stores a `graph`, a `nodes` array and a `edges array`.
2. The directed graph will be used to guide the dialogue.
3. `Nodes` are a powerful data structure that have the instructions to be processed. I gave an example below.
4. Each node have at least a `text` and  a `trigger`. Text are just the current npc speech. `trigger` is the command that needs to be used by the player to trigger this specific node.
5. The graph structure implementation is up to the developer in charge
6. After graph is implemented we need a interpreter to interpret the nodes and do the actions.

https://github.com/jinc0930/Clue/blob/1c40fac26590f59733e3f698544e49488f08f910/character.c#L383-L409

## Tasks
- [x] #46 
- [x] types and functions definition now in `character.c`
- [x] Graph implementation @jinc0930 
  - [x] makeGraph (directed graph: adjacency list)
  - [x] addNode
  - [x] addEdge
  - [x] findNext
  - [x] findEntry
  - [x] tests graph
- [ ] Node Interpreter implementation @mishimalisa  
  - [x] makeNode basic
  - [x] makeNode buy
  - [x] makeNode trade
  - [x] tests for buying
  - [ ] basic tests
  - [ ] getTriggers
  - [ ] nextDialogue
    - [ ] Basic dialogue
    - [ ] Trade dialogue
    - [ ] Flags (Pin/Inactive/End)
